# Generated by Django 3.2.4 on 2021-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNum', models.CharField(max_length=9)),
                ('studentName', models.CharField(max_length=100)),
                ('appointDate', models.DateTimeField(blank=True, null=True)),
                ('appointDesc', models.CharField(max_length=250)),
            ],
        ),
    ]
